### ISSUE TITLE
Support displaying status bar item for 1 cursor

### ISSUE THREAD

**Issue by jneuendorf** [lexicalunit/cursor-indicator#2]
Hi,

if there is only 1 cursor nothing will currently be displayed in the status bar. 

https://github.com/lexicalunit/cursor-indicator/blob/241b0bd006d7860108e5dd691d4f2eccd264b02d/lib/cursor-indicator-view.coffee#L23-L30

I would find it useful to have an option in the settings for _also display something for a single cursor_.
That way it can be more explicit and still optional.
My suggestion would look something like

```coffee
update: (editor) ->
    len = editor?.getCursors().length
    if len > 1 or atom.config.get('cursor-indicator.alwaysShow') is true
        @textContent = "#{@displayPrefix}#{len}#{@displaySuffix}"
        @style.display = 'inline-block'
    else
        @textContent = ''
        @style.display = 'none'
```

If you like the idea I could create a Pull Request if you prefer.
I guess the test `when cursors are added` would have to be adjusted in that case.

**Comment by lexicalunit** [comment]
Try out v1.3.0 👍

**Comment by jneuendorf** [comment]
Thanks for the quick update - works great :)
